---
version: v1
policies:
  - type: commit
    spec:
      header:
        length: 72
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false # Don't require body for simple changes
      dco: false
      gpg: false # Don't require GPG signing
      spellcheck:
        locale: GB
      conventional:
        types:
          - feat # New feature
          - fix # Bug fix
          - docs # Documentation changes
          - style # Code style changes (formatting, etc.)
          - refactor # Code refactoring
          - test # Adding or updating tests
          - chore # Maintenance tasks
          - ci # CI/CD changes
          - perf # Performance improvements
          - revert # Reverting changes
          - build # Build system changes
        scopes:
          - website
          - content
          - tests
          - ci
          - deps
        descriptionLength: 72
