name: Check if Hugo page has been updated
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Find outdated pages
        run: |
          find content -type f -name "*.md" | while read -r page; do
            modified=$(git log -1 --format=%ct -- $page)
            now=$(date +%s)
            days_since_modified=$(( (now - modified) / 86400 ))

            # Extract the date from the Markdown front matter
            date_field=$(grep -i '^date:' $page | head -n 1 | sed 's/date:\s*//i')
            if [ -n "$date_field" ]; then
              date=$(date -d "$date_field" +%s)
              days_since_update=$(( (now - date) / 86400 ))
              if [ $days_since_update -gt 30 ]; then
                echo "Page $page hasn't been updated for $days_since_update days"
                issue_title="Page $page hasn't been updated for $days_since_update days"
                issue_body="The following page hasn't been updated for $days_since_update days: $page"
                curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -d '{"title":"'$issue_title'", "body":"'$issue_body'"}' "https://api.github.com/repos/$GITHUB_REPOSITORY/issues"
              fi
            else
              echo "No date field found in $page"
            fi
          done
