name: Check if Hugo page has been updated
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MODIFIED_DAYS: 9

jobs:
  check-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Find outdated pages
        run: |
          find content -type f -name "*.md" | while read -r page; do
            modified=$(git log -1 --format=%ct -- $page)
            now=$(date +%s)
            days_since_modified=$(( (now - modified) / 86400 ))
            if [ $days_since_modified -gt "$MODIFIED_DAYS" ]; then
              echo "Page $page hasn't been updated for more than $MODIFIED_DAYS"
              issue_title="Page $page hasn't been updated for $days_since_modified days"
              issue_body="The following page hasn't been updated for $days_since_modified days: $page"
              echo "Creating issue for page: $page"
              curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -d '{"title":"'$issue_title'", "body":"'$issue_body'", "labels":["content-outdated"]}' "https://api.github.com/repos/$GITHUB_REPOSITORY/issues"
            else
              echo "Page $page is up to date, it was modified $days_since_modified days ago"
            fi
          done
