---
name: Misspell
on: [pull_request]
jobs:
  misspell:
    name: Misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run misspell check
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "UK"
          reporter: "github-pr-review"
          path: "content/talks.md"
          level: "error"
